name: pypsa
channels:
- conda-forge
dependencies:
- python>=3.8
- numpy
- scipy
- pandas>=0.24.0
- xarray
- netcdf4
- pytables
- matplotlib
- networkx>=1.10
- linopy
- pyomo>=5.7.0
- cartopy>=0.16
- glpk
- linopy>=0.1.1
- deprecation
#  - coincbc
#  - gurobi::gurobi
